name: HQCsOneBlock
version: 1.2.2
main: org.hqcplays.hqcsoneblock.HQCsOneBlock
api-version: 1.21
depend: [ProtocolLib]
commands:
  bcshop:
    description: Opens the Block Coin shop
    usage: /bcshop
  cheat:
    description: Opens the cheat menu
    usage: /cheat
  lobby:
    description: Teleports the player back to the lobby
    usage: /lobby
  island:
    description: Teleports the player to their island. Creates one if they don't have one
    usage: /island
  flea:
    description: Opens the Flea Market
    usage: /flea
  list:
    description: Allows players to list items on the Flea Market
    usage: /list
  inbox:
    description: Allows players to view items in their inbox
    usage: /inbox
  progression:
    description: Opens the Progression menu
    usage: /progression
  profiles:
    description: Opens the profile selection menu
    usage: /profiles
  warps:
    description: Opens the warps menu
    usage: /warps
